PACKAGE_NAME="tty0tty"
PACKAGE_VERSION="1.2"
BUILT_MODULE_NAME[0]="tty0tty"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
AUTOINSTALL="yes"
MAKE[0]="make ARCH=${ARCH} KVERSION=${kernelver}"
CLEAN="make clean"
